FROM python:3.11-slim-bullseye

WORKDIR /subgen

ADD requirements.txt /subgen/requirements.txt

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
        python3 \
        python3-pip \
        ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

ADD launcher.py /subgen/launcher.py
ADD subgen.py /subgen/subgen.py

CMD [ "bash", "-c", "python3 -u launcher.py" ]
