ARG CUDA_VER=12.4.1-runtime-ubuntu24.04

FROM nvidia/cuda:${CUDA_VER}
WORKDIR /subgen

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
        python3 \
        python3-pip \
        ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

RUN pip3 install --upgrade pip setuptools \
    && pip3 install torch torchaudio --index-url https://download.pytorch.org/whl/cu124 \
    && pip3 install qwen-asr \
    && pip3 install fastapi uvicorn python-multipart huggingface_hub

ENV PYTHONUNBUFFERED=1

ADD subgen-qwen3asr.py /subgen/subgen-qwen3asr.py

ENTRYPOINT [ "/bin/bash", "-c" ]
CMD [ "python3 -u subgen-qwen3asr.py" ]
