name: Build_Subgen_Dockerfile_GPU

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 
            gkovalechyn/subgen:${{ github.ref_name }}-gpu-cu118
