name: Build docker image

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace version string  
        run: sed -i 's/__SUBGEN_VERSION__/${{ github.ref_name }}/' subgen.py
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Free Disk Space (Ubuntu)      
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 
            gkovalechyn/subgen:${{ github.ref_name }}-gpu-cu118
